---
galaxy_info:
  author: Matthew Montgomery
  description: 
  company: 
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: EL
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - system
dependencies: []
